import { Address } from './address'
import { Injectable } from "@angular/core";

@Injectable()
export class ProviderInformation extends Address {
    public ProfessionList: string
    public PracticeAddress: string
    public PracticeCity: string
    public PracticeState: string
    public PracticeZipCode: string
    public PracticeCountry: string  
    public FaxNumber: string
    public SocialSecurity: string 
    public Speciality: string
    public NPI: string
    public MedicareValidation: string
    public Education: string
    public NursingSchool: string 
    public NursingYearOfGraduation: string
    public PgEducation: string
    public PgYearOfGraduation: string
    public IsBoardEligible: boolean
    public IsBoardCertified: boolean
    public BoardName: string
    public CertifiedNumber: string
    public Gender: string
    public DOB: Date
    public ContactPerson: string
    public IsOwnPractice: boolean
    public LanguageKnown: string
    public CreatedDate: Date
    public DEARegistraionStatus: string 
    public IsFullTimeJob: boolean
    public Hours: string
    public ScheduledDays: string
    public PreferedTypeOfConsults: string 
    public ScheduleComment: string
    public CVFileName: string
    public OtherFileName: string
    public SubmittedDate: Date
    public SignatureName: string 
    public IsDiciplinaryByOthers: boolean
    public IsStateProfessionalLicense: boolean
    public IsHospitalPrivilegesDenied: boolean
    public IsPendingMalpractice: boolean
    public IsConvictedVilationOfLaw: boolean
    public IsProblemWithDrugAlcohol: boolean
    public IsDeclinedanyInsuraceCompany: boolean
    public IsPhysicalConditionFine: boolean
    public ExplanationNotes: string 

    public profession =  [
          { name: 'MD',  selected: false, id: 1 },
          { name: 'DO',  selected: false, id: 2 },
          { name: 'PA',  selected: false, id:  3},
          { name: 'NP',  selected: false, id: 4 },
          { name: 'NP-BC',  selected: false, id: 5 },
          { name: 'RN-BC',  selected: false, id: 6 },
          { name: 'APRN',  selected: false, id: 7 },
          { name: 'FNP',  selected: false, id: 8 },
          { name: 'CRNA',  selected: false, id: 9 },
        ]; 

    public ContactPersionList = [
		{ name : 'Rob Berton - LTUSA & Encore' },	
		{ name : 'Beau Berton - LTUSA & Encore' },	
		{ name : 'Dr. Joseph Palumbo, DO' },	
		{ name : 'Aaron Summerlin - LTUSA & Encore' },	
		{ name : 'DJ Wells -  Encore' },	
		{ name : 'Ed Kiefer - LTUSA & Encore' },	
		{ name : 'Elizabeth Wall - LTUSA & Encore' },	
		{ name : 'Elizabeth Wall - LTUSA' },	
		{ name : 'Eric Greenwald - Encore' },	
		{ name : 'Eric Gruen, DPM - LTUSA & Encore' },	
		{ name : 'Jim Angel - Encore' },	
		{ name : 'Karen Young - LTUSA' },	
		{ name : 'Liz Page - LTUSA & Encore' },	
		{ name : 'Robin Darnell - Encore' },	
		{ name : 'Shay Hutchison - Encore' },	
		{ name : 'Structural Health' },	
		{ name : 'Tanya Wells - Encore' } 
    ]
}

@Injectable()
export class CountryList {
  public values: any = [ 
  {country:'Afghanistan' } ,
  {country:'Aland Islands' } ,
  {country:'Albania' } ,
  {country:'Algeria' } ,
  {country:'American Samoa' } ,
  {country:'Andorra' } ,
  {country:'Angola' } ,
  {country:'Anguilla' } ,
  {country:'Antarctica' } ,
  {country:'Antigua and Barbuda' } ,
  {country:'Argentina' } ,
  {country:'Armenia' } ,
  {country:'Aruba' } ,
  {country:'Australia' } ,
  {country:'Austria' } ,
  {country:'Azerbaijan' } ,
  {country:'Bahamas' } ,
  {country:'Bahrain' } ,
  {country:'Bangladesh' } ,
  {country:'Barbados' } ,
  {country:'Belarus' } ,
  {country:'Belgium' } ,
  {country:'Belize' } ,
  {country:'Benin' } ,
  {country:'Bermuda' } ,
  {country:'Bhutan' } ,
  {country:'Bolivia' } ,
  {country:'Bonaire, Sint Eustatius and Saba' } ,
  {country:'Bosnia and Herzegovina' } ,
  {country:'Botswana' } ,
  {country:'Bouvet Island' } ,
  {country:'Brazil' } ,
  {country:'British Indian Ocean Territory' } ,
  {country:'Brunei' } ,
  {country:'Bulgaria' } ,
  {country:'Burkina Faso' } ,
  {country:'Burundi' } ,
  {country:'Côte d Ivoire' } ,
  {country:'Cambodia' } ,
  {country:'Cameroon' } ,
  {country:'Canada' } ,
  {country:'Cape Verde' } ,
  {country:'Cayman Islands' } ,
  {country:'Central African Republic' } ,
  {country:'Chad' } ,
  {country:'Chile' } ,
  {country:'China' } ,
  {country:'Christmas Island' } ,
  {country:'Cocos (Keeling) Islands' } ,
  {country:'Colombia' } ,
  {country:'Comoros' } ,
  {country:'Congo' } ,
  {country:'Cook Islands' } ,
  {country:'Costa Rica' } ,
  {country:'Croatia' } ,
  {country:'Cuba' } ,
  {country:'Curacao' } ,
  {country:'Cyprus' } ,
  {country:'Czech Republic' } ,
  {country:'Denmark' } ,
  {country:'Djibouti' } ,
  {country:'Dominica' } ,
  {country:'Dominican Republic' } ,
  {country:'East Timor' } ,
  {country:'Ecuador' } ,
  {country:'Egypt' } ,
  {country:'El Salvador' } ,
  {country:'Equatorial Guinea' } ,
  {country:'Eritrea' } ,
  {country:'Estonia' } ,
  {country:'Ethiopia' } ,
  {country:'Falkland Islands (Malvinas)' } ,
  {country:'Faroe Islands' } ,
  {country:'Fiji' } ,
  {country:'Finland' } ,
  {country:'France' } ,
  {country:'French Guiana' } ,
  {country:'French Polynesia' } ,
  {country:'French Southern Territories' } ,
  {country:'Gabon' } ,
  {country:'Gambia' } ,
  {country:'Georgia' } ,
  {country:'Germany' } ,
  {country:'Ghana' } ,
  {country:'Gibraltar' } ,
  {country:'Greece' } ,
  {country:'Greenland' } ,
  {country:'Grenada' } ,
  {country:'Guadeloupe' } ,
  {country:'Guam' } ,
  {country:'Guatemala' } ,
  {country:'Guernsey' } ,
  {country:'Guinea' } ,
  {country:'Guinea-Bissau' } ,
  {country:'Guyana' } ,
  {country:'Haiti' } ,
  {country:'Heard Island and McDonald Islands' } ,
  {country:'Holy See' } ,
  {country:'Honduras' } ,
  {country:'Hong Kong' } ,
  {country:'Hungary' } ,
  {country:'Iceland' } ,
  {country:'India' } ,
  {country:'Indonesia' } ,
  {country:'Iran' } ,
  {country:'Iraq' } ,
  {country:'Ireland' } ,
  {country:'Isle of Man' } ,
  {country:'Israel' } ,
  {country:'Italy' } ,
  {country:'Jamaica' } ,
  {country:'Japan' } ,
  {country:'Jersey' } ,
  {country:'Jordan' } ,
  {country:'Kazakhstan' } ,
  {country:'Kenya' } ,
  {country:'Kiribati' } ,
  {country:'Kosovo' } ,
  {country:'Kuwait' } ,
  {country:'Kyrgyzstan' } ,
  {country:'Laos' } ,
  {country:'Latvia' } ,
  {country:'Lebanon' } ,
  {country:'Lesotho' } ,
  {country:'Liberia' } ,
  {country:'Libya' } ,
  {country:'Liechtenstein' } ,
  {country:'Lithuania' } ,
  {country:'Luxembourg' } ,
  {country:'Macao' } ,
  {country:'Macedonia' } ,
  {country:'Madagascar' } ,
  {country:'Malawi' } ,
  {country:'Malaysia' } ,
  {country:'Maldives' } ,
  {country:'Mali' } ,
  {country:'Malta' } ,
  {country:'Marshall Islands' } ,
  {country:'Martinique' } ,
  {country:'Mauritania' } ,
  {country:'Mauritius' } ,
  {country:'Mayotte' } ,
  {country:'Mexico' } ,
  {country:'Micronesia' } ,
  {country:'Moldova' } ,
  {country:'Monaco' } ,
  {country:'Mongolia' } ,
  {country:'Montenegro' } ,
  {country:'Montserrat' } ,
  {country:'Morocco' } ,
  {country:'Mozambique' } ,
  {country:'Myanmar' } ,
  {country:'Namibia' } ,
  {country:'Nauru' } ,
  {country:'Nepal' } ,
  {country:'Netherlands' } ,
  {country:'New Caledonia' } ,
  {country:'New Zealand' } ,
  {country:'Nicaragua' } ,
  {country:'Niger' } ,
  {country:'Nigeria' } ,
  {country:'Niue' } ,
  {country:'Norfolk Island' } ,
  {country:'North Korea' } ,
  {country:'Northern Mariana Islands' } ,
  {country:'Norway' } ,
  {country:'Oman' } ,
  {country:'Pakistan' } ,
  {country:'Palau' } ,
  {country:'Palestine' } ,
  {country:'Panama' } ,
  {country:'Papua New Guinea' } ,
  {country:'Paraguay' } ,
  {country:'Peru' } ,
  {country:'Philippines' } ,
  {country:'Pitcairn' } ,
  {country:'Poland' } ,
  {country:'Portugal' } ,
  {country:'Puerto Rico' } ,
  {country:'Qatar' } ,
  {country:'Reunion' } ,
  {country:'Romania' } ,
  {country:'Russia' } ,
  {country:'Rwanda' } ,
  {country:'Saint Barthelemy' } ,
  {country:'Saint Helena, Ascension and Tristan da Cunha' } ,
  {country:'Saint Kitts and Nevis' } ,
  {country:'Saint Lucia' } ,
  {country:'Saint Martin (French part)' } ,
  {country:'Saint Pierre and Miquelon' } ,
  {country:'Saint Vincent and the Grenadines' } ,
  {country:'Samoa' } ,
  {country:'San Marino' } ,
  {country:'Sao Tome and Principe' } ,
  {country:'Saudi Arabia' } ,
  {country:'Senegal' } ,
  {country:'Serbia' } ,
  {country:'Seychelles' } ,
  {country:'Sierra Leone' } ,
  {country:'Singapore' } ,
  {country:'Sint Maarten (Dutch part)' } ,
  {country:'Slovakia' } ,
  {country:'Slovenia' } ,
  {country:'Solomon Islands' } ,
  {country:'Somalia' } ,
  {country:'South Africa' } ,
  {country:'South Georgia and the South Sandwich Islands' } ,
  {country:'South Korea' } ,
  {country:'South Sudan' } ,
  {country:'Spain' } ,
  {country:'Sri Lanka' } ,
  {country:'Sudan' } ,
  {country:'Suriname' } ,
  {country:'Svalbard and Jan Mayen' } ,
  {country:'Swaziland' } ,
  {country:'Sweden' } ,
  {country:'Switzerland' } ,
  {country:'Syria' } ,
  {country:'Taiwan' } ,
  {country:'Tajikistan' } ,
  {country:'Tanzania' } ,
  {country:'Thailand' } ,
  {country:'Timor-Leste' } ,
  {country:'Togo' } ,
  {country:'Tokelau' } ,
  {country:'Tonga' } ,
  {country:'Trinidad and Tobago' } ,
  {country:'Tunisia' } ,
  {country:'Turkey' } ,
  {country:'Turkmenistan' } ,
  {country:'Turks and Caicos Islands' } ,
  {country:'Tuvalu' } ,
  {country:'Uganda' } ,
  {country:'Ukraine' } ,
  {country:'United Arab Emirates' } ,
  {country:'United Kingdom' } ,
  {country:'United States' } ,
  {country:'United States Minor Outlying Islands' } ,
  {country:'Uruguay' } ,
  {country:'Uzbekistan' } ,
  {country:'Vanuatu' } ,
  {country:'Vatican City' } ,
  {country:'Venezuela' } ,
  {country:'Vietnam' } ,
  {country:'Virgin Islands, British' } ,
  {country:'Virgin Islands, U.S.' } ,
  {country:'Wallis and Futuna' } ,
  {country:'Western Sahara' } ,
  {country:'Yemen' } ,
  {country:'Zambia' } ,
  {country:'Zimbabwe' }];
}